---
email:
  sender: kundu.lab.keb310@gmail.com
  pw: email_pw.txt
  reciever: jobrienweiss@umass.edu
  send: false
common_args:
  experiment_number: 0
  dataset: CIFAR10
  gpu: null
  best_model_metric: val_acc1
  debug: 10
  save_one_checkpoint: true
experiments:
- model_type: resnet20
  model_path:
  quantization:
  prune_method: RandomPruning
  attack_method:
  prune_compression: 2
  finetune_epochs: 1
  kwargs: {}
